### ISSUE TITLE
Question on Mixed Integer Quadratic Programming (MIQP) support

### ISSUE THREAD

**Issue by skent259** [r-opt/rmpk#50]
Hi,

Is MIQP solving possible with your package? 

Sorry if this is a naive question, but I see that your README suggests that this is a supported type of problem. However, I can't find any documentation or use case for that specific problem.  I looked through the vignettes and some of the code.  

From what I can tell, it uses the ROI backend, but according to their paper documentation, they don't have a MIQP solver (see Table 1 of https://epub.wu.ac.at/5858/1/ROI_StatReport.pdf). So far, the only way in R I have found to solve this type of problem is the gurobi backend...

Many thanks,
Sean

**Comment by dirkschumacher** [comment]
Modelling _should_ work, but as you noted there might not be a ROI solver interface for a compatible solver. I guess that would need to get developed first (or a MOI compatible Gurobi package).

What are you trying to do?

**Comment by skent259** [comment]
Ah, I understand the distinction.  It makes sense that your package wouldn't have any problem building this MIQP problem, even if the ROI backend doesn't have an available solver.  Sorry, this clearly isn't a problem with the package; I was just hoping to find an open-source MIQP solver in R to solve a variant on SVM with some extra constraints and binary variables and thought you might know something that I didn't.
